name: alquran_alkareem
description: "AlQuran AlKareem App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.2
  get: ^4.6.6
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.2
  theme_button: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lamsz_quran_api: ^0.0.4
  animated_splash_screen: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
    - family: OttomanFont
      fonts:
        - asset: assets/fonts/Othmani-Regular.ttf
    - family: AayatQuraan
      fonts:
        - asset: assets/fonts/Aayat Quraan_032_Regular.ttf
flutter_intl:
  enabled: true
